import { v4 as uuidv4 } from "uuid";
import cardIndumentaria from "./images/card-indumentaria.jpg";

const dataArray = [
  {
    id: uuidv4(),
    name: "Helsinki",
    category: "mats",
    sale: false,
    offerPrice: 15,
    description: "Stylist apartment in center of the city",
    price: 5200,
    image: cardIndumentaria,
    stock: 2,
  },
  {
    id: uuidv4(),
    name: "Turku",
    category: "mats",
    sale: false,
    offerPrice: 15,
    description: "Nice apartment in center of Helsinki",
    price: 8000,
    image: cardIndumentaria,
    stock: 2,
  },
  {
    id: uuidv4(),
    name: "Calza",
    price: 11500,
    category: "elementos-meditacion",
    sale: true,
    offerPrice: 10,
    description: "Arty interior in 1900 wooden house",
    image: cardIndumentaria,
    stock: 3,
  },
  {
    id: uuidv4(),
    name: "Helsinki",
    category: "elementos-meditacion",
    sale: true,
    description: "Stylist apartment in center of the city",
    price: 10000,
    offerPrice: 25,
    image: cardIndumentaria,
    stock: 4,
  },
  {
    id: uuidv4(),
    name: "Helsinki",
    category: "elementos-yoga",
    sale: false,
    description: "Stylist apartment in center of the city",
    price: 5200,
    offerPrice: 15,
    image: cardIndumentaria,
    stock: 2,
  },
  {
    id: uuidv4(),
    name: "Helsinki",
    category: "elementos-yoga",
    sale: false,
    description: "Stylist apartment in center of the city",
    price: 5200,
    offerPrice: 15,
    image: cardIndumentaria,
    stock: 2,
  },
  {
    id: uuidv4(),
    name: "Helsinki",
    category: "elementos-yoga",
    sale: false,
    description: "Stylist apartment in center of the city",
    price: 5200,
    offerPrice: 15,
    image: cardIndumentaria,
    stock: 2,
  },
  {
    id: uuidv4(),
    name: "Helsinki",
    category: "elementos-yoga",
    sale: false,
    description: "Stylist apartment in center of the city",
    price: 5200,
    offerPrice: 15,
    image: cardIndumentaria,
    stock: 2,
  },
  {
    id: uuidv4(),
    name: "Helsinki",
    category: "elementos-yoga",
    sale: false,
    description: "Stylist apartment in center of the city",
    price: 5200,
    offerPrice: 15,
    image: cardIndumentaria,
    stock: 2,
  },
  {
    id: uuidv4(),
    name: "Helsinki",
    category: "elementos-yoga",
    sale: false,
    description: "Stylist apartment in center of the city",
    price: 5200,
    offerPrice: 15,
    image: cardIndumentaria,
    stock: 2,
  },
  {
    id: uuidv4(),
    name: "Helsinki",
    category: "elementos-yoga",
    sale: false,
    description: "Stylist apartment in center of the city",
    price: 5200,
    offerPrice: 15,
    image: cardIndumentaria,
    stock: 2,
  },
  {
    id: uuidv4(),
    name: "Calza larga",
    category: "elementos-yoga",
    sale: true,
    description: "Stylist apartment in center of the city",
    price: 5200,
    offerPrice: 10,
    image: cardIndumentaria,
    stock: 1,
  },
];

export default dataArray;
